# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA:  prepared
  TRAINDED_DATA:  train.tsv
  TEST_DATA:  test.tsv
  FEATURIZED_DATA:  features
  FEATURIZED_DATA_TRAIN:  train.pkl
  FEATURIZED_DATA_TEST:  test.pkl
  MODEL_NAME: model.pkl

metrics:
  SCORES: scores.json

plots:
  PRC:  prc.json
  ROC:  roc.json

source_data:
  data_dir: data
  data_file:  data.xml

source_download_dirs:
  - path_to_data_1
  - path_to_data_1

local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2
